# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_oceandata.ui'
#
# Created: Wed Sep 24 13:26:16 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OceanData(object):
    def setupUi(self, OceanData):
        OceanData.setObjectName(_fromUtf8("OceanData"))
        OceanData.resize(451, 487)
        self.plainTextEdit = QtGui.QPlainTextEdit(OceanData)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 310, 431, 121))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.btnDownload = QtGui.QPushButton(OceanData)
        self.btnDownload.setGeometry(QtCore.QRect(170, 450, 114, 32))
        self.btnDownload.setObjectName(_fromUtf8("btnDownload"))
        self.label_5 = QtGui.QLabel(OceanData)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.infoTextEdit = QtGui.QPlainTextEdit(OceanData)
        self.infoTextEdit.setEnabled(False)
        self.infoTextEdit.setGeometry(QtCore.QRect(10, 90, 431, 51))
        self.infoTextEdit.setObjectName(_fromUtf8("infoTextEdit"))
        self.widget = QtGui.QWidget(OceanData)
        self.widget.setGeometry(QtCore.QRect(20, 150, 185, 26))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.comboBoxTime = QtGui.QComboBox(self.widget)
        self.comboBoxTime.setObjectName(_fromUtf8("comboBoxTime"))
        self.comboBoxTime.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBoxTime)
        self.widget1 = QtGui.QWidget(OceanData)
        self.widget1.setGeometry(QtCore.QRect(20, 190, 401, 28))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.startDate = QtGui.QDateEdit(self.widget1)
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName(_fromUtf8("startDate"))
        self.horizontalLayout_2.addWidget(self.startDate)
        self.endDate = QtGui.QDateEdit(self.widget1)
        self.endDate.setCalendarPopup(True)
        self.endDate.setDate(QtCore.QDate(2000, 1, 20))
        self.endDate.setObjectName(_fromUtf8("endDate"))
        self.horizontalLayout_2.addWidget(self.endDate)
        self.widget2 = QtGui.QWidget(OceanData)
        self.widget2.setGeometry(QtCore.QRect(20, 230, 171, 26))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBoxRes = QtGui.QComboBox(self.widget2)
        self.comboBoxRes.setObjectName(_fromUtf8("comboBoxRes"))
        self.comboBoxRes.addItem(_fromUtf8(""))
        self.comboBoxRes.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBoxRes)
        self.widget3 = QtGui.QWidget(OceanData)
        self.widget3.setGeometry(QtCore.QRect(20, 270, 401, 25))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.widget3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.txtPath = QtGui.QLineEdit(self.widget3)
        self.txtPath.setObjectName(_fromUtf8("txtPath"))
        self.horizontalLayout_4.addWidget(self.txtPath)
        self.toolButton = QtGui.QToolButton(self.widget3)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.widget4 = QtGui.QWidget(OceanData)
        self.widget4.setGeometry(QtCore.QRect(20, 50, 391, 26))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.widget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBoxDatasets = QtGui.QComboBox(self.widget4)
        self.comboBoxDatasets.setEnabled(True)
        self.comboBoxDatasets.setObjectName(_fromUtf8("comboBoxDatasets"))
        self.comboBoxDatasets.addItem(_fromUtf8(""))
        self.comboBoxDatasets.addItem(_fromUtf8(""))
        self.comboBoxDatasets.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.comboBoxDatasets)

        self.retranslateUi(OceanData)
        QtCore.QObject.connect(self.btnDownload, QtCore.SIGNAL(_fromUtf8("clicked()")), OceanData.accept)
        QtCore.QObject.connect(self.toolButton, QtCore.SIGNAL(_fromUtf8("clicked()")), OceanData.open)
        QtCore.QObject.connect(self.comboBoxDatasets, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), OceanData.show)
        QtCore.QMetaObject.connectSlotsByName(OceanData)

    def retranslateUi(self, OceanData):
        OceanData.setWindowTitle(_translate("OceanData", "OceanData", None))
        self.btnDownload.setText(_translate("OceanData", "Download", None))
        self.label_5.setText(_translate("OceanData", "NASA Oceancolor Downloader", None))
        self.label_6.setText(_translate("OceanData", "Time period:", None))
        self.comboBoxTime.setItemText(0, _translate("OceanData", "Annual", None))
        self.label_2.setText(_translate("OceanData", "Date range:", None))
        self.endDate.setDisplayFormat(_translate("OceanData", "dd-MM-yyyy", None))
        self.label_3.setText(_translate("OceanData", "Resolution:", None))
        self.comboBoxRes.setItemText(0, _translate("OceanData", "4km", None))
        self.comboBoxRes.setItemText(1, _translate("OceanData", "9km", None))
        self.label.setText(_translate("OceanData", "Download to:", None))
        self.txtPath.setText(_translate("OceanData", "/Users/Ireland/rsr/qgis-dev/", None))
        self.toolButton.setText(_translate("OceanData", "...", None))
        self.label_4.setText(_translate("OceanData", "Dataset:", None))
        self.comboBoxDatasets.setItemText(0, _translate("OceanData", "-", None))
        self.comboBoxDatasets.setItemText(1, _translate("OceanData", "hi", None))
        self.comboBoxDatasets.setItemText(2, _translate("OceanData", "AQUA MODIS Chlorophyll Concentration", None))

